<a href="https://colab.research.google.com/github/Dead-d-eal/Sagar_AIML/blob/main/10_3_23.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

:Write a python program the base class contain addition of two no but the derive class contain multiplication of samr number 

In [2]:
class A:
  def add(self,a,b):
    return a+b
class B(A):
  def mul(self,a,b):
    return a*b
c=B()
a=int(input("Enter the vaue of a: "))
b=int(input("Enter the value of b: "))
print("The addition is:",c.add(a,b))
print("The multiplication is:",c.mul(a,b))

Enter the vaue of a: 2
Enter the value of b: 3
The addition is: 5
The multiplication is: 6


write a python program using multilevel inheritance to devlop a calculator which contains four derived of derive class and one child class

In [3]:
class A:
  def add(self,x,y):
    return x+y
class B(A):
  def sub(self,x,y):
    return x-y
class C(B):
  def mul(self,x,y):
    return x*y
class D(C):
  def div(self,x,y):
    return x/y
e=D()
x=int(input("Enter the value of x: "))
y=int(input("Enter the value of y: "))
ch=int(input("Enter your choice: "))
if ch==1:
  print(e.add(x,y))
elif ch==2:
  print(e.sub(x,y))
elif ch==3:
  print(e.mul(x,y))
elif ch==4:
  print(e.div(x,y))

Enter the value of x: 2
Enter the value of y: 3
Enter your choice: 3
6


Write a python program to input employee infaormation employee id, name, basic salary,hra=15%,pa=5% and medical allowence is 5000 and its 10% more than 10000 using sinle inheritance the base cls contains all the employee informations but the derive class contaions net salary of a employee with all informations.

Numpy 

In [4]:
import numpy as np
print(np.__version__)

1.22.4


In [5]:
import numpy
list=[10,20,30,40,50]
arr=numpy.array(list)
print(arr)

[10 20 30 40 50]


In [6]:
import numpy as np
list=[10,20,30,40,50]
arr=np.array(list)
print('size:',arr.size)
print('data type:',arr.dtype)
print('dimension:',arr.ndim)
print('shape:',arr.shape)

size: 5
data type: int64
dimension: 1
shape: (5,)


In [7]:
import numpy as np
list=[10,20,30],[60,70,80]
arr=np.array(list)
print(arr)

[[10 20 30]
 [60 70 80]]


In [8]:
import numpy as np
list=[10,20,30],[60,70,80]
arr=np.array(list)
print(arr[1])

[60 70 80]


In [9]:
import numpy as np
list=[10,20,30],[60,70,80]
arr=np.array(list)
print(arr[1][1])

70


In [11]:
import numpy as np
list=[[[1,2,3],[4,5,6],[7,8,9]]]
arr=np.array(list)
print(arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [13]:
import numpy as np
list=[10,20,30,40,50]
arr=np.array(list)
print('Element')
for ele in arr:
  print(ele*2)

Element
20
40
60
80
100


In [16]:
import numpy as np
arr=np.array([1,2,3,4],ndmin=6)
print(arr)
print('Dimensions of array:',arr.ndim)

[[[[[[1 2 3 4]]]]]]
Dimensions of array: 6
